services:
  mailagent-api:
    build:
      context: .
      dockerfile: MailAgent.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Database: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      
      Llm__Provider: ${LLM_PROVIDER}
      Llm__BaseUrl: ${LLM_BASE_URL}
      Llm__FastModel: ${LLM_FAST_MODEL}
      Llm__MainModel: ${LLM_MAIN_MODEL}
      
      MailImport__Enabled: "true"
      MailImport__Folders__0: "Releases"
      
      DailyDigest__Enabled: "true"
      DailyDigest__OutputLanguage: ${PREFER_LANGUAGE}
      
      MailServer__Provider: ${MAIL_PROVIDER}
      MailServer__Username: ${MAIL_USERNAME}
      MailServer__Password: ${MAIL_PASSWORD}
      
      MailServer__Ews__Url: ${MAIL_EWS_URL}
      MailServer__Ews__Domain: ${MAIL_EWS_DOMAIN}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always

  mailagent-web:
    build:
      context: .
      dockerfile: MailAgent.Web/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      UseHttpsRedirection: "false"
      MailAgentApi__BaseUrl: http://mailagent-api:8080
      MailAgentApi__TimeoutMinutes: "10"
      ConnectionStrings__Database: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
